version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-range.yml

jobs:
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_RECIPE=4.6.x-dev
        - REQUIRE_MFA=4.0.x-dev
        - PHPUNIT_TEST=1

before_script:
  - if [[ $REQUIRE_MFA ]]; then composer require --no-update silverstripe/mfa:"$REQUIRE_MFA"; fi
